import { ValuesNoteType } from "@/lib/types/global"
import { INFO_MASTER_S4_STATIC } from "./utils"

const INFO_M1_IAD_DATA: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Apprentissage artificiel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Calcul différentiel et optimisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse de Données",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et data mining",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modèles graphiques probabilistes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique1",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Python",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 18,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 4,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 2",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Représentation des connaissances et raisonnement",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Fondements du Data Science",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse et Traitement des Images Numériques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modélisation et simulation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données No SQL et Fast data",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Programmation Orientée Objet Avancée",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
]

/* -------------------------------------- */

const INFO_M2_IAD_DATA: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Apprentissage artificiel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Calcul différentiel et optimisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse de Données",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et data mining",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modèles graphiques probabilistes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique1",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Python",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 18,
  },
  {
    ...INFO_MASTER_S4_STATIC,
  },
]

export const INFO_M1_IAD = {
  title: "Master 1 Intelligence Artificielle et Digitalisation",
  etablissement: "Université Ibn khaldoun Tiaret",
  slug: "info-m1-iad",
  data: INFO_M1_IAD_DATA,
}

export const INFO_M2_IAD = {
  title: "Master 2 Intelligence Artificielle et Digitalisation",
  etablissement: "Université Ibn khaldoun Tiaret",
  slug: "info-m2-iad",
  data: INFO_M2_IAD_DATA,
}
