import { ValuesNoteType } from "@/lib/types/global"
import { INFO_MASTER_S4_STATIC } from "./utils"

const INFO_M1_GI_DATA: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 8,
      Fondamentale2: 10,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 4,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Logique pour intelligence artificielle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Systèmes à Base de Connaissance",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Méthodes de simulation à événements discrets",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 100,
          moduleName: "Aspects des graphes à la recherche opérationnelle",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Optimisation en recherche opérationnelle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes et outils de Modélisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes formelles et outils de vérification",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName: "Sécurité Web / e-learning",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais Premier niveau",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 10,
      Fondamentale2: 8,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 5,
      Fondamentale2: 4,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Web service",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Ontologies et web sémantique",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 100,
          moduleName: "Ergonomie Web",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Traitement et analyse des d'images",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Vision artificielle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Réseaux et télécommunication",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et Datamining",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 100,
          moduleName: "Modèles mathématiques du traitement du signal",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName:
            "DSP / Micro-contrôleurs / Analyse et synthèse des systèmes logiques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais niveau 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
]

/* -------------------------------------- */

const INFO_M2_GI_DATA: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 18,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 9,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Théories avancées du traitement de signal",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Parallélisme et Clustering",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Systèmes Temps Réel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Gestion projet informatique",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 100,
          moduleName: "Recherche bibliographique",
          tdTpWeight: 0,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName:
            "Législation et déontologie du travail / Ethique professionnelle en enseignement",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais niveau 3",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
  {
    ...INFO_MASTER_S4_STATIC,
  },
]

export const INFO_M1_GI = {
  title: "Master 1 Génie Informatique",
  etablissement: "Université Ibn khaldoun Tiaret",
  slug: "info-m1-gi",
  data: INFO_M1_GI_DATA,
}

export const INFO_M2_GI = {
  title: "Master 2 Génie Informatique",
  etablissement: "Université Ibn khaldoun Tiaret",
  slug: "info-m2-gi",
  data: INFO_M2_GI_DATA,
}
