import type { Metadata } from "next"
import "./globals.css"
import { inter } from "./styles/fonts"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full scroll-smooth" suppressHydrationWarning>
      <body
        style={inter.style}
        className={cn("h-full antialiased", inter.className)}
        suppressHydrationWarning
      >
        <main className="min-h-screen w-full flex flex-col items-center justify-center">
          {children}
        </main>
        <Toaster position="top-center" richColors theme="light" />
      </body>
    </html>
  )
}
