import { StaticCalculatorType, ValuesNoteType } from "./types/global"

const staticValues = {
  examScore: 0.0,
  tdScore: 0.0,
  tpScore: 0.0,
  moduleMoy: 0.0,
  moduleMoyCof: 0,
}

const INFO_MASTER_S4_STATIC: ValuesNoteType = {
  title: "semaster 2",
  groupedModules: {
    Fondamentale1: [
      {
        moduleName: "Projet de fin de cycle",
        coefficient: 1,
        credit: 30,
        examWeight: 100,
        tdTpWeight: 0,
        examType: "none",
        unityType: "Fondamentale1",
        ...staticValues,
      },
    ],
  },
  totalCoefficientSum: 1,
  totalCreditSum: 30,
  coefficientSum: {
    Fondamentale1: 1,
  },
  creditSum: {
    Fondamentale1: 30,
  },
  // ------------ //
  unityMoy: {
    Fondamentale1: 0.0,
  },
  creditSumMoy: {
    Fondamentale1: 0,
  },
  finalResult: 0.0,
  totalCreditSumMoy: 0,
}

// -------------------------------------- //

const INFO_L3_ISIL_STATIC = {
  totalCoefficientSum: 17,
  totalCreditSum: 30,
  coefficientSum: {
    Fondamentale1: 6,
    Fondamentale2: 6,
    Methodologique: 4,
    Transversale: 1,
  },
  creditSum: {
    Fondamentale1: 10,
    Fondamentale2: 10,
    Methodologique: 8,
    Transversale: 2,
  },
  // ------------ //
  unityMoy: {
    Fondamentale1: 0.0,
    Fondamentale2: 0.0,
    Methodologique: 0.0,
    Transversale: 0.0,
  },
  creditSumMoy: {
    Fondamentale1: 0,
    Fondamentale2: 0,
    Methodologique: 0,
    Transversale: 0,
  },
  finalResult: 0.0,
  totalCreditSumMoy: 0,
}

export const INFO_L3_ISIL: ValuesNoteType[] = [
  {
    title: "semaster 1",
    groupedModules: {
      Fondamentale1: [
        {
          moduleName: "Système d'information distribué",
          coefficient: 4,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "Système d'aide à la décision",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
      ],

      Fondamentale2: [
        {
          moduleName: "Génie Logiciel",
          coefficient: 4,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
        {
          moduleName: "Interface Homme Machine",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
      ],

      Methodologique: [
        {
          moduleName: "Administration des Systèmes d'information",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Methodologique",
          ...staticValues,
        },
        {
          moduleName: "Programmation avancée pour le Web",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Methodologique",
          ...staticValues,
        },
      ],

      Transversale: [
        {
          moduleName: "Economie numérique et veille stratégique",
          coefficient: 1,
          credit: 2,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Transversale",
          ...staticValues,
        },
      ],
    },
    ...INFO_L3_ISIL_STATIC,
  },
  {
    title: "semaster 2",
    groupedModules: {
      Fondamentale1: [
        {
          moduleName: "Recherche d'information",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "Sécurité Informatique",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Fondamentale1",
          ...staticValues,
        },
      ],

      Fondamentale2: [
        {
          moduleName: "Données semi structurées",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
        {
          moduleName: "Système d'exploitation 2",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
      ],

      Methodologique: [
        {
          moduleName: "Projet",
          coefficient: 3,
          credit: 6,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Methodologique",
          ...staticValues,
        },
        {
          moduleName: "Business Intelligence",
          coefficient: 1,
          credit: 2,
          examWeight: 0,
          tdTpWeight: 100,
          examType: "TD",
          unityType: "Methodologique",
          ...staticValues,
        },
      ],

      Transversale: [
        {
          moduleName: "Rédaction Scientifique",
          coefficient: 1,
          credit: 2,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Transversale",
          ...staticValues,
        },
      ],
    },
    ...INFO_L3_ISIL_STATIC,
  },
]

// -------------------------------------- //

const INFO_M1_GL_S1_STATIC = {
  totalCoefficientSum: 16,
  totalCreditSum: 30,
  coefficientSum: {
    Fondamentale1: 5,
    Fondamentale2: 4,
    Methodologique: 4,
    Decouverte: 2,
    Transversale: 1,
  },
  creditSum: {
    Fondamentale1: 10,
    Fondamentale2: 8,
    Methodologique: 9,
    Decouverte: 2,
    Transversale: 1,
  },
  // ------------ //
  unityMoy: {
    Fondamentale1: 0.0,
    Fondamentale2: 0.0,
    Methodologique: 0.0,
    Decouverte: 0.0,
    Transversale: 0.0,
  },
  creditSumMoy: {
    Fondamentale1: 0,
    Fondamentale2: 0,
    Methodologique: 0,
    Decouverte: 0,
    Transversale: 0,
  },
  finalResult: 0.0,
  totalCreditSumMoy: 0,
}
const INFO_M1_GL_S2_STATIC = {
  totalCoefficientSum: 16,
  totalCreditSum: 30,
  coefficientSum: {
    Fondamentale1: 4,
    Fondamentale2: 5,
    Methodologique: 4,
    Decouverte: 2,
    Transversale: 1,
  },
  creditSum: {
    Fondamentale1: 8,
    Fondamentale2: 10,
    Methodologique: 9,
    Decouverte: 2,
    Transversale: 1,
  },
  // ------------ //
  unityMoy: {
    Fondamentale1: 0.0,
    Fondamentale2: 0.0,
    Methodologique: 0.0,
    Decouverte: 0.0,
    Transversale: 0.0,
  },
  creditSumMoy: {
    Fondamentale1: 0,
    Fondamentale2: 0,
    Methodologique: 0,
    Decouverte: 0,
    Transversale: 0,
  },
  finalResult: 0.0,
  totalCreditSumMoy: 0,
}

export const INFO_M1_GL: ValuesNoteType[] = [
  {
    title: "semaster 1",
    groupedModules: {
      Fondamentale1: [
        {
          moduleName: "Génie Logiciel",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "Programmation fonctionnelle",
          coefficient: 3,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
      ],

      Fondamentale2: [
        {
          moduleName: "Base de Données et Data Maining",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
        {
          moduleName: "Archetecture et Administration de SGBD",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
      ],

      Methodologique: [
        {
          moduleName: "Compléxité Algorithmique",
          coefficient: 2,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Methodologique",
          ...staticValues,
        },
        {
          moduleName: "Gestion de la Qualité",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Methodologique",
          ...staticValues,
        },
      ],

      Decouverte: [
        {
          moduleName: "Logique pour intelligence artificielle",
          coefficient: 2,
          credit: 2,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Decouverte",
          ...staticValues,
        },
      ],

      Transversale: [
        {
          moduleName: "Anglais 1",
          coefficient: 1,
          credit: 1,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Transversale",
          ...staticValues,
        },
      ],
    },
    ...INFO_M1_GL_S1_STATIC,
  },
  {
    title: "semaster 2",
    groupedModules: {
      Fondamentale1: [
        {
          moduleName: "Spécification et Conception Logiciels",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "Architecture et Devloppement  Logiciels",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
      ],

      Fondamentale2: [
        {
          moduleName: "Construction d'Applications Réparties",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
        {
          moduleName: "Programmation Web",
          coefficient: 1,
          credit: 2,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale2",
          ...staticValues,
        },
        {
          moduleName: "Fondement de l' Intelligence artificielle",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Fondamentale2",
          ...staticValues,
        },
      ],

      Methodologique: [
        {
          moduleName: "Validation Formelle des Système Informatique",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Methodologique",
          ...staticValues,
        },
        {
          moduleName: "Mathématique Appliqués",
          coefficient: 2,
          credit: 4,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD",
          unityType: "Methodologique",
          ...staticValues,
        },
      ],

      Decouverte: [
        {
          moduleName: "Sécurité Informatique",
          coefficient: 2,
          credit: 2,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Decouverte",
          ...staticValues,
        },
      ],

      Transversale: [
        {
          moduleName: "Anglais 2",
          coefficient: 1,
          credit: 1,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Transversale",
          ...staticValues,
        },
      ],
    },
    ...INFO_M1_GL_S2_STATIC,
  },
]

// -------------------------------------- //

const INFO_M2_GL_S3_STATIC = {
  totalCoefficientSum: 17,
  totalCreditSum: 30,
  coefficientSum: {
    Fondamentale1: 9,
    Methodologique: 5,
    Decouverte: 1,
    Transversale: 2,
  },
  creditSum: {
    Fondamentale1: 18,
    Methodologique: 9,
    Decouverte: 1,
    Transversale: 2,
  },
  // ------------ //
  unityMoy: {
    Fondamentale1: 0.0,
    Fondamentale2: 0.0,
    Methodologique: 0.0,
    Decouverte: 0.0,
    Transversale: 0.0,
  },
  creditSumMoy: {
    Fondamentale1: 0,
    Fondamentale2: 0,
    Methodologique: 0,
    Decouverte: 0,
    Transversale: 0,
  },
  finalResult: 0.0,
  totalCreditSumMoy: 0,
}

export const INFO_M2_GL: ValuesNoteType[] = [
  {
    title: "semaster 1",
    groupedModules: {
      Fondamentale1: [
        {
          moduleName: "Dév App Mob sous Android",
          coefficient: 3,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "Maintenance Logicielles",
          coefficient: 3,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
        {
          moduleName: "XML Avancé et Web 2.0",
          coefficient: 3,
          credit: 6,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TP",
          unityType: "Fondamentale1",
          ...staticValues,
        },
      ],

      Methodologique: [
        {
          moduleName: "Gestion des projets Informatique",
          coefficient: 3,
          credit: 5,
          examWeight: 60,
          tdTpWeight: 40,
          examType: "TD_TP",
          unityType: "Methodologique",
          ...staticValues,
        },
        {
          moduleName: "Techniques Expression et de RS",
          coefficient: 2,
          credit: 4,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Methodologique",
          ...staticValues,
        },
      ],

      Decouverte: [
        {
          moduleName: "Législation et Déont Travail",
          coefficient: 1,
          credit: 1,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Decouverte",
          ...staticValues,
        },
      ],

      Transversale: [
        {
          moduleName: "Anglais 3",
          coefficient: 2,
          credit: 2,
          examWeight: 100,
          tdTpWeight: 0,
          examType: "none",
          unityType: "Transversale",
          ...staticValues,
        },
      ],
    },
    ...INFO_M2_GL_S3_STATIC,
  },
  {
    ...INFO_MASTER_S4_STATIC,
  },
]

// -------------------------------------- //
// From database
export const INFO_M1_IAD: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Apprentissage artificiel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Calcul différentiel et optimisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse de Données",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et data mining",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modèles graphiques probabilistes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique1",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Python",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 18,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 4,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 2",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Représentation des connaissances et raisonnement",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Fondements du Data Science",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse et Traitement des Images Numériques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modélisation et simulation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données No SQL et Fast data",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Programmation Orientée Objet Avancée",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
]

// -------------------------------------- //
// From database
export const INFO_M2_IAD: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 1,
      Transversale: 3,
      Fondamentale1: 9,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 1,
      Transversale: 2,
      Fondamentale1: 5,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Apprentissage artificiel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Calcul différentiel et optimisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseaux de neurones et Apprentissage profond 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Analyse de Données",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et data mining",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Modèles graphiques probabilistes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 100,
          moduleName: "Anglais technique et scientifique1",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 60,
          moduleName: "Python",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 18,
  },
  {
    ...INFO_MASTER_S4_STATIC,
  },
]
// -------------------------------------- //
// From database
export const INFO_L2: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Transversale: 2,
      Fondamentale1: 11,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Transversale: 1,
      Fondamentale1: 6,
      Fondamentale2: 5,
      Methodologique: 4,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Architecture des ordinateurs",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Algorithmique et structure de données 3",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Système d'information",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Théorie des graphes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes numériques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Logique mathématique",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Langue Etrangère 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 16,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Fondamentale1: 10,
      Fondamentale2: 10,
      Methodologique: 8,
      Transversale: 2,
    },
    finalResult: 0,
    creditSumMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Fondamentale1: 5,
      Fondamentale2: 6,
      Methodologique: 4,
      Transversale: 1,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Théorie des langages",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Système d'exploitation 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Bases de données",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseau",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Programmation orienté objet",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Développement d'application Web",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Langue Etrangère 3",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 16,
  },
]
// -------------------------------------- //
// From database
export const INFO_M1_GI: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 8,
      Fondamentale2: 10,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 4,
      Fondamentale2: 5,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Logique pour intelligence artificielle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Systèmes à Base de Connaissance",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Méthodes de simulation à événements discrets",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 100,
          moduleName: "Aspects des graphes à la recherche opérationnelle",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Optimisation en recherche opérationnelle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes et outils de Modélisation",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes formelles et outils de vérification",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName: "Sécurité Web / e-learning",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais Premier niveau",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 10,
      Fondamentale2: 8,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 5,
      Fondamentale2: 4,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Web service",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Ontologies et web sémantique",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 100,
          moduleName: "Ergonomie Web",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Traitement et analyse des d'images",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Vision artificielle",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Réseaux et télécommunication",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 3,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Bases de données avancées et Datamining",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 100,
          moduleName: "Modèles mathématiques du traitement du signal",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName:
            "DSP / Micro-contrôleurs / Analyse et synthèse des systèmes logiques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais niveau 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
]
// -------------------------------------- //
// From database
export const INFO_M2_GI: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Methodologique: 0,
    },
    creditSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 18,
      Methodologique: 9,
    },
    finalResult: 0,
    creditSumMoy: {
      Decouverte: 0,
      Transversale: 0,
      Fondamentale1: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Decouverte: 2,
      Transversale: 1,
      Fondamentale1: 9,
      Methodologique: 5,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Théories avancées du traitement de signal",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Parallélisme et Clustering",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Systèmes Temps Réel",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Gestion projet informatique",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 100,
          moduleName: "Recherche bibliographique",
          tdTpWeight: 0,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Decouverte: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Decouverte",
          examWeight: 60,
          moduleName:
            "Législation et déontologie du travail / Ethique professionnelle en enseignement",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 1,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Anglais niveau 3",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 17,
  },
  {
    ...INFO_MASTER_S4_STATIC,
  },
]
// -------------------------------------- //

export const staticCalculator: StaticCalculatorType[] = [
  {
    title: "Informatique 2 LMD",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-l2",
    data: INFO_L2,
  },
  {
    title: "Informatique 3 LMD ISIL",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-l3-isil",
    data: INFO_L3_ISIL,
  },
  {
    title: "Master 1 Génie Logiciel",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m1-gl",
    data: INFO_M1_GL,
  },
  {
    title: "Master 2 Génie Logiciel",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m2-gl",
    data: INFO_M2_GL,
  },
  {
    title: "Master 1 Génie Informatique",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m1-gi",
    data: INFO_M1_GI,
  },
  {
    title: "Master 2 Génie Informatique",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m2-gi",
    data: INFO_M2_GI,
  },
  {
    title: "Master 1 Intelligence Artificielle et Digitalisation",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m1-iad",
    data: INFO_M1_IAD,
  },
  {
    title: "Master 2 Intelligence Artificielle et Digitalisation",
    etablissement: "Université Ibn khaldoun Tiaret",
    slug: "info-m2-iad",
    data: INFO_M2_IAD,
  },
]

export function findStaticCalculator(
  slug: string
): StaticCalculatorType | null {
  for (const calculator of staticCalculator) {
    if (calculator.slug === slug) {
      return calculator
    }
  }
  return null
}
// -------------------------------------- //
