import { ValuesNoteType } from "@/lib/types/global"

const INFO_L2_DATA: ValuesNoteType[] = [
  {
    title: "Semestre 1",
    unityMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Transversale: 2,
      Fondamentale1: 11,
      Fondamentale2: 9,
      Methodologique: 8,
    },
    finalResult: 0,
    creditSumMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Transversale: 1,
      Fondamentale1: 6,
      Fondamentale2: 5,
      Methodologique: 4,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Architecture des ordinateurs",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 6,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Algorithmique et structure de données 3",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Système d'information",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Théorie des graphes",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Méthodes numériques",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TD",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Logique mathématique",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Langue Etrangère 2",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 16,
  },
  {
    title: "Semestre 2",
    unityMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    creditSum: {
      Fondamentale1: 10,
      Fondamentale2: 10,
      Methodologique: 8,
      Transversale: 2,
    },
    finalResult: 0,
    creditSumMoy: {
      Transversale: 0,
      Fondamentale1: 0,
      Fondamentale2: 0,
      Methodologique: 0,
    },
    coefficientSum: {
      Fondamentale1: 5,
      Fondamentale2: 6,
      Methodologique: 4,
      Transversale: 1,
    },
    groupedModules: {
      Fondamentale1: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Théorie des langages",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale1",
          examWeight: 60,
          moduleName: "Système d'exploitation 1",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Fondamentale2: [
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Bases de données",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
        {
          credit: 5,
          tdScore: 0,
          tpScore: 0,
          examType: "TD_TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Fondamentale2",
          examWeight: 60,
          moduleName: "Réseau",
          tdTpWeight: 40,
          coefficient: 3,
          moduleMoyCof: 0,
        },
      ],
      Methodologique: [
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Programmation orienté objet",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
        {
          credit: 4,
          tdScore: 0,
          tpScore: 0,
          examType: "TP",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Methodologique",
          examWeight: 60,
          moduleName: "Développement d'application Web",
          tdTpWeight: 40,
          coefficient: 2,
          moduleMoyCof: 0,
        },
      ],
      Transversale: [
        {
          credit: 2,
          tdScore: 0,
          tpScore: 0,
          examType: "none",
          examScore: 0,
          moduleMoy: 0,
          unityType: "Transversale",
          examWeight: 100,
          moduleName: "Langue Etrangère 3",
          tdTpWeight: 0,
          coefficient: 1,
          moduleMoyCof: 0,
        },
      ],
    },
    totalCreditSum: 30,
    totalCreditSumMoy: 0,
    totalCoefficientSum: 16,
  },
]

export const INFO_L2 = {
  title: "Informatique 2 LMD",
  etablissement: "Université Ibn khaldoun Tiaret",
  slug: "info-l2",
  data: INFO_L2_DATA,
}
